name: Node.js CI

on:
  push:
    branches:
      - main
      - build_with_anis_api_endpoint
  pull_request:
    branches:
      - main
      - build_with_anis_api_endpoint

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npx expo export -p web
      - name: Archive web
        uses: actions/upload-artifact@v3
        with:
          name: web-build
          path: dist
